language: python
python:
  - "3.4"

services:
  - postgresql

env:
  global:
    - BUILD_ON_TRAVIS=true
    - AUTHOME_SECRET_KEY=travis
    - AUTHOME_DATABASE_NAME=mydb
    - AUTHOME_DATABASE_USER=postgres
    - AUTHOME_DATABASE_PASSWORD=test12#$
    - AUTHOME_DATABASE_HOST=localhost
    - AUTHOME_DATABASE_PORT=5432
    - AUTHOME_ADMIN_URL=travisadmin
    - ENV EMAIL_HOST=smtp.gmail.com
    - ENV EMAIL_HOST_USER test@gmail.com
    - ENV EMAIL_HOST_PASSWORD test
    - ENV EMAIL_PORT 587

  matrix:
    - DJANGO_VERSION=1.9.12 DB=postgresql

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libpq-dev
  - sudo apt-get install -y python3-dev

install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION

before_script:
  - psql -c "CREATE DATABASE mydb;" -U postgres
  - python manage.py makemigrations

script:
  - python manage.py migrate
