language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - DJANGO='Django==1.9.*'
matrix:
  exclude:
    - python: "3.4"
      env: DJANGO='Django==1.9.*'
    - python: "3.5"
      env: DJANGO='Django==1.9.*'
    - python: "3.6"
      env: DJANGO='Django==1.9.*'
install:
  - pip install $DJANGO
